#version: '2.9'
name: expense
networks:
  default:
    name: expense
    external: true
services:
  mysql:
    image: mysql:v1.0
    container_name: mysql
  backend:
    image: backend:v1.0
    container_name: backend
    command: sh -c "sleep 20 && node /app/index.js"
    depends_on:
      - mysql
  frontend:
    image: frontend:v1.0
    container_name: fronttend
    depends_on:
      - backend
    ports:
    - "80:80"